import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Responsivenav from "../../components/Home/Navbar/Responsivenav";
import Footer from "../../components/Home/Footer/Footer";
import ScroolToUp from "../../components/Home/ScroolToUp/ScroolToUp";
 
const font = Inter({
  weight:["100","200","300","400","500","600","700","800","900"],
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "Dilip's Protofolio",
  description: "Generated by using next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${font.className}  antialiased bg-[#0d0d1f]`}
      >
        <Responsivenav />
        {children}
        <Footer />
        <ScroolToUp />
      </body>
    </html>
  );
}
